### ISSUE TITLE
"Sender" Example Code Bootlooping

### ISSUE THREAD

**Issue by Jordandarabos** [ElectronicCats/Bast-WAN#1]
Hey,

When I upload the "sender" example code to the RAK4260 with the ElectronicCats bootloader installed it gets stuck in a bootloop(the receiver code works fine).  When I comment out the "LoRa.endPacket()" line it will run through the program but will not send any packets(as expected). So I expect that this is the issue but I can't quite figure out _why_. Please help. Thanks!

UPDATE 1/29:

So... my power supply ended up being bad which was causing a voltage dip during transmission. New power supply... Now the program runs fine however It's not sending any packets. In the serial monitor I get the first "Sending packet: 0" but then the LED just goes on and off with no more data in the serial monitor and nothing being received by my receiver(which I've confirmed works with another LoRa module.)

**Comment by sabas1080** [comment]
@Jordandarabos what version of the Arduino Core Electronic cats do you have?

**Comment by Jordandarabos** [comment]
Hey Sabas,

Thanks for the reply! I’m currently running version 1.0.6.

**Comment by Jordandarabos** [comment]
Hey,

So I was using the Radiohead library on the receiver module... I just thought to maybe switch over to the Sandeepmistry lib and now it works fine... Still doesn't show anything in the "sending" serial monitor from the RAK4260 but I'm now receiving the packets. So I guess it works fine and I'm just an idiot lol.

**Comment by sabas1080** [comment]
@Jordandarabos keep us up to date and let us know if your problem is solved, we are willing to help

**Comment by Jordandarabos** [comment]
@sabas1080  It seems to be working fine now... Have you guys had any luck using the sleep modes with the Arduino IDE? I can get it to work with RAKS example code but I was hoping to use the Arduino IDE. Thanks!

**Comment by sabas1080** [comment]
Do you have examples? We can try port examples to arduino @Jordandarabos

**Comment by Jordandarabos** [comment]
@Sabas I was able to get this one working in Atmel Studio and got my power consumption down to 1uA! It would be awesome to be able to use it in the Arduino IDE!


RAK4260 low power demo https://github.com/RAKWireless/RAK4260_Low_Power_demo

**Comment by Jordandarabos** [comment]
@sabas1080*

**Comment by sabas1080** [comment]
ok, I have open issue for your request feature #2
