### ISSUE TITLE
SPI Flash alternative to GD25Q16C

### ISSUE THREAD

**Issue by jaimelaborda** [ElectronicCats/Bast-WAN#5]
Dear all,

There is an alternative chip to the U4 (GD25Q16C) SPI Flash on the BastWAN easily accessible in Europe? I have seen that we can get it from LCSC but I was searching for Farnell/RS/Digikey alternative.

What is this chip intended for? Program store? Is it mandatory?

Thank you very much.

Best regards,
Jaime

**Comment by sabas1080** [comment]
Hi @jaimelaborda the chip is available in mouser europe https://eu.mouser.com/Search/Refine?Keyword=GD25Q16C

the chip is not mandatory, only is more memory
