### ISSUE TITLE
[Help] Flashing UF2 USB bootloader

### ISSUE THREAD

**Issue by jaimelaborda** [ElectronicCats/Bast-WAN#6]
Hi,

I just wanted to know if there is a guide to or something like that to flash the BastWAN, I have just built some boards myself but I don't know where the UF2 USB bootloader can be found.

Best regards,
Jaime.

**Comment by sabas1080** [comment]
Hi @jaimelaborda 

The bootloader is in our Arduino Core https://github.com/ElectronicCats/ArduinoCore-samd/tree/master/bootloaders/bastwan

if you can send us photos of your boards, we would love to see them

**Comment by jaimelaborda** [comment]
Hi @sabas1080 

Thank you very much for your reply and help.

I have managed to successfully upload the bootloader to the board using a JLink and the .bin you provide me! Cool!!

I attach you some photos of our boards (we are from [MakersUPV](http://makersupv.com/) at Valencia, Spain). I have to thank you and the ElectronicsCats team for bringing that cool board to the open-source community. I love feather board form factor, and having Arduino support for RAK chips is awesome!. You guys have done a great job! Viva Mexico!!

![IMG_20200923_101237](https://user-images.githubusercontent.com/12583019/93986021-19e36780-fd86-11ea-8425-255a0c6f8f1d.jpg)
![IMG_20200923_101227](https://user-images.githubusercontent.com/12583019/93986029-1bad2b00-fd86-11ea-9b22-c97d6d19d51b.jpg)


Stay safe.

Best regards,
Jaime.

**Comment by sabas1080** [comment]
Nice work!

Un abrazo hasta la madre patria
