### ISSUE TITLE
SPI flash

### ISSUE THREAD

**Issue by henriAbel** [ElectronicCats/Bast-WAN#8]
Don't see any reference to SPI flash in schematics. Which PIN is used for flash CS?

**Comment by Jorgeuri** [comment]
CS is in the D10 (PA14) PIN.

**Comment by henriAbel** [comment]
Are there any examples how to read/write from flash? I have tried to adapt some libraries but none of them even detect FLASH.

**Comment by capuchino68** [comment]
What version do you have?




> Are there any examples how to read/write from flash? I have tried to adapt some libraries but none of them even detect FLASH.

**Comment by henriAbel** [comment]
BAST v2.0 BastWan is behind the PCB

**Comment by sabas1080** [comment]
@henriAbel 
bastwan v2.0 does not have SPI flash, check schematic https://github.com/ElectronicCats/BastWAN/blob/master/Hardware/Bast_WAN.pdf

version 1.3 and 1.2 included flash, but in new versions we removed SAMR34 it does not support circuitpython

**Comment by henriAbel** [comment]
Would be nice to keep repo and store page up to date.
Store still has reference to the 2 MB SPI flash
https://electroniccats.com/store/bastwan/

**Comment by sabas1080** [comment]
updated in store, thank you for your comments @henriAbel
